source 'https://rubygems.org'
gem "oily_png", "~>1.0.2"
gem "jasmine", "~>1.2.0"
gem "rake", "~>0.9.2.2"
gem "guard", "~>1.0.3"
gem "guard-coffeescript", "~>0.6.0"
gem "coffee-script-source", "~>1.3.3"
gem "guard-compass", "~>0.0.6"
gem "json", "~>1.7.3"
gem "guard-rocco", "~>0.0.3"
